# Name of your workflow
name: Deploy to Firebase Hosting

# Run this workflow on every push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Safely converts the secret to a single-line JSON string and replaces the placeholder
      - name: Add Firebase Config
        run: |
          CONFIG_JSON_STRING=$(node -e "console.log(JSON.stringify(${{ secrets.FIREBASE_CONFIG }}))")
          sed -i "s|'__FIREBASE_CONFIG_JSON_PLACEHOLDER__'|${CONFIG_JSON_STRING}|g" index.html

      # 3. Deploys the code to Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: akshat-expense-tracker-app