# Name of your workflow
name: Deploy to Firebase Hosting

# Run this workflow on every push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Safely replaces the multi-line placeholder
      - name: Add Firebase Config
        env:
          FIREBASE_CONFIG_SECRET: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          # Use awk for a robust multi-line replacement
          awk -v var="$FIREBASE_CONFIG_SECRET" '{gsub(/__FIREBASE_CONFIG__/, var)}1' index.html > index.tmp && mv index.tmp index.html

      # 3. Deploys the code to Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: akshat-expense-tracker-app